spring.application.name=venuva

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=Waselny615@gmail.com
spring.mail.password=uhnp sryl muzi bqiy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
